version: '3.6'
services:
  shib-service:
    image: uscdev/shib-service
    ports:
      - 80:80
      - 443:443
    environment:
      - SERVER_NAME=${SERVER_NAME}
    networks:
      proxy:
    secrets:
      - apache.crt
      - apache.key
      - sp-key.pem
      - sp-cert.pem
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
networks:
  proxy:
    external: true
secrets:
  apache.crt:
    external: true
  apache.key:
    external: true
  sp-key.pem:
    external: true
  sp-cert.pem:
    external: true
